format_version: 3
pipelines:
  lock_behavior: lockOnFailure
  mv-java-quickstart:
    group: TEST
    materials:
      repo:
        git: https://github.com/manu863018/MV.git
        master: gocd
    stages:
      - Build:
          jobs:
            building:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments:
                      - "clean"
                      - "assemble"
                      - "-p"
                      - "quickstart"
              artifacts:
                - build:
                    source: quickstart/build/libs/*.jar
                    destination: Build
      - Test:
          jobs:
            Unit_Test:
              tasks:
                - exec:
                    command: ./quickstart/gradlew
                    arguments: 
                      - clean
                      - test
                      - -p
                      - quickstart                      
              artifacts:
                - build:
                    source: quickstart/build/reports/tests/test/**/*
                    destination: html
                - test:
                    source: quickstart/build/test-results/test/*.xml
                    destination: xml                    
              tabs:
                unit_test: html/index.html
                    